### PR TITLE
Add codeowners from STACKIT

### PR DESCRIPTION
**Pull request by timebertt**
**How to categorize this PR?**

/area os open-source
/kind enhancement

**What this PR does / why we need it**:

At STACKIT, we offer flatcar as the primary OS for worker nodes. Hence, we rely on this extension.
As other interested parties faced out CoreOS/flatcar in their environments, we probably have the highest stakes in keeping this extension up-to-date.
To simplify things, this PR adds two codeowners from STACKIT (particular persons are not set in stone).
This allows us to formally assume responsibility for this repository.

TODO:

- [x] https://github.com/gardener/gardener-extension-os-coreos/issues/97

**Which issue(s) this PR fixes**:

See https://gardener-cloud.slack.com/archives/C045DSWJZB9/p1711461148599709

**Special notes for your reviewer**:

I recall, that we cannot add contributors from outside SAP to the gardener org. With this, we cannot add STACKIT colleagues to the @gardener/gardener-extension-os-coreos-maintainers group.
If this has changed meanwhile, let me know and we can drop this PR and use the group instead.

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by gardener-robot-ci-1** [comment]
Thank you @timebertt for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Comment by timebertt** [comment]
@zkdev Now that @dergeberl and I are part of @gardener, we could also use the @gardener/gardener-extension-os-coreos-maintainers team instead of adding our usernames to `CODEOWNERS`. Then we could drop this PR.
WDYT?

**Comment by zkdev** [comment]
I prefer to explicitly mention you, next to core-os GitHub team, in CODEOWNERS file to avoid unintended side-effects.

**Comment by timebertt** [comment]
Ok, fine for me 👍

**Review by plkokanov — APPROVED** [review]

**Pull request merged**
