### PR TITLE
Make repo compliant

### PR DESCRIPTION
**Pull request by RaphaelVogel**
**How to categorize this PR?**
/area compliance
/kind cleanup

**What this PR does / why we need it**:
* Deleted `NOTICE.md` file
* Updated `CONTRIBUTING.md` file
* Created/Updated `LICENSE` file
  * Deleted `LICENSE.md` file
* Created/Updated `.reuse/dep5` file
* Created/Updated `LICENSES` folder
* Added badge for reuse compliance in `README.md` file and registered repo with REUSE API
* Updated `example/controller-registration.yaml` 
* License/Copyright header replacement for 'non-go' files
  * Makefile
  * hack/update-github-templates.sh
* License/Copyright header replacement for 'go' files
  * cmd/gardener-extension-os-coreos/main.go
  * cmd/gardener-extension-os-coreos/app/app.go
  * charts/gardener-extension-os-coreos/doc.go
  * hack/tools.go
  * pkg/controller/operatingsystemconfig/coreos_reconcile.go
  * pkg/controller/operatingsystemconfig/add.go
  * pkg/controller/operatingsystemconfig/actuator.go
  * pkg/controller/operatingsystemconfig/coreos_reconcile_test.go
  * pkg/controller/operatingsystemconfig/actuator_test.go
  * pkg/controller/operatingsystemconfig/operatingsystemconfig_suite_test.go
  * pkg/controller/operatingsystemconfig/coreos/types.go
  * pkg/controller/operatingsystemconfig/coreos/coreos_suite_test.go

**Additional information**
To keep this repository compliant, CODEOWNERS must maintain their third party dependencies in the vendor folder using `.reuse/dep5` file. To prevent constant maintenance effort, it is **highly recommended** to remove the `vendor` folder. In this case no third party dependencies of the vendor folder must be maintained anymore!

### CODE REVIEW

**Comment by plkokanov** [comment]
I ran `reuse lint` locally however it said that 
> Unfortunately, your project is not compliant with version 3.0 of the REUSE Specification :-(

It seems to be because of the `vendor` directory, so I wonder if this is expected for now. Here's the output: [lint.txt](https://github.com/gardener/gardener-extension-os-coreos/files/14862427/lint.txt)

**Comment by RaphaelVogel** [comment]
@plkokanov I added the missing licenses in the `LICENSES` folder. Now reuse does not complain anymore. Thx

**Review by plkokanov — APPROVED** [review]
/lgtm

**Pull request merged**
