### PR TITLE
Vendor gardener v1.25

### PR DESCRIPTION
**Pull request by vpnachev**
**What this PR does / why we need it**:
Vendor gardener/gardener@v1.25.0

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

### CODE REVIEW

**Comment by BeckerMax** [comment]
changes look good.
Do wee need an adaption of rbac similiar to: https://github.com/gardener/gardener-extension-os-ubuntu/commit/48785ccc8b73619e75ea2e70a6c30786f09a6218#diff-41789a182f8a5211570ef167a23c156a5581e90eb7573408d4ab930202aebcb7R44-R52
?

**Review by BeckerMax — CHANGES_REQUESTED** [review]
see comment

**Comment by vpnachev** [comment]
Good catch, thanks!

**Review by BeckerMax — APPROVED** [review]

**Comment by BeckerMax** [comment]
`make generate` is still needed.

**Comment by vpnachev** [comment]
Should be good now.

**Review by BeckerMax — APPROVED** [review]

**Pull request merged**
