### PR TITLE
Update GH PR template

### PR DESCRIPTION
**Pull request by vpnachev**
**What this PR does / why we need it**:
Update github PR template.

**Which issue(s) this PR fixes**:
Ref https://github.com/gardener/cc-utils/pull/497

/invite @petersutter 

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

### CODE REVIEW

**Review by petersutter — DISMISSED** [review]
/lgtm, thanks!

**Comment by rfranzke** [comment]
What about rather introducing something like https://github.com/gardener/gardener-extension-networking-calico/blob/master/hack/update-github-templates.sh?

**Comment by vpnachev** [comment]
> What about rather introducing something like https://github.com/gardener/gardener-extension-networking-calico/blob/master/hack/update-github-templates.sh?

Makes sense, it is implemented now.

**Review by rfranzke — APPROVED** [review]
/lgtm

**Pull request merged**
