### PR TITLE
Compatibility with logrotate in /usr/bin

### LINKED ISSUE #54: Containerd logrotate broken on certain Flatcar versions
**How to categorize this issue?**

/area os
/kind bug

**What happened**:

The `containerd-logrotate` service fails with:

```
Dec 14 11:40:00 shoot--fcloud--mad-prod-shared-wrk-sw1c-n2dc8-z1-77b7c-spxkx systemd[678791]: containerd-logrotate.service: Failed at step EXEC spawning /usr/sbin/logrotate: No such file or directory
```

The logrotate binary indeed isn't in /usr/sbin, but in /usr/bin.

**What you expected to happen**:

The containerd configuration specifies the correct location of the logrotate binary and thus runs successfully.

**How to reproduce it (as minimally and precisely as possible)**:

Spin up the environment below. Probably equal Gardener (including this extension) versions and the Flatcar version are sufficient.

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant): 1.59.2
- Extension version: 1.15.0
- Kubernetes version (use `kubectl version`): 1.24.8
- Cloud provider or hardware configuration: Google Cloud
- Others: Flatcar version 3227.2.4

### PR DESCRIPTION
**Pull request by lukasgr90**
**How to categorize this PR?**

/area os
/kind bug

**What this PR does / why we need it**:

Recent flatcar images has the logrotate binary not in `/usr/sbin` anymore, but in `/usr/bin`. Thus this PR extends the `run-command.service` (doing Containerd & Flatcar / Core OS related patches) to check for the alternate location of logrotate. If it finds the binary under `/usr/bin` it patches the path in `/etc/systemd/system/containerd-logrotate.service`.

**Which issue(s) this PR fixes**:
Fixes #54

**Special notes for your reviewer**: -

**Release note**:

```other operator
bugfix user 
fixes containerd-lograte unit for Flatcar images with logrotate in /usr/bin
```

### CODE REVIEW

**Comment by gardener-robot-ci-2** [comment]
Thank you @lukasgr90 for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Review by MrBatschner — APPROVED** [review]
/lgtm

**Pull request merged**
